// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Noodles.Models;

public partial class Reservation
{
    [Key]
    [Column("ReservationID")]
    public int ReservationId { get; set; }

    
    [Column("UserID")]
    public int UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ReservationDateTime { get; set; }

    public int? TableNumber { get; set; }

    [JsonIgnore]
    [ForeignKey("UserId")]
    [InverseProperty("Reservations")]
    public virtual User User { get; set; }

    public void ValidateReservationId()
    {
        if (ReservationId < 1)
        {
            throw new ArgumentOutOfRangeException("ReservationId must be a positive number!");
        }
    }

    public void ValidateUserId()
    {
        if (UserId < 1)
        {
            throw new ArgumentOutOfRangeException("UserId must be a positive number!");
        }
    }

    public void ValidateReservationDateTime()
    {
        if (ReservationDateTime < DateTime.Now)
        {
            throw new ArgumentOutOfRangeException("ReservationDateTime cannot be in the past.");
        }
    }

    public void ValidateTableNumber()
    {
        if (TableNumber < 1)
        {
            throw new ArgumentOutOfRangeException("TableNumber must be a positive number!");
        }
    }
}